PaperShareService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(
settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'),
    path('papers/new/', views.papers_new, name='papers_new'),
    path('papers/<int:pk>/', views.papers_detail, name='papers_detail'),
    path('papers/<int:pk>/delete/', views.papers_delete, name='papers_delete'),
    path('papers/<str:category>/', views.papers_category, name='papers_category'),
    path('signup/', views.signup, name='signup'),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='app/login.html'),
        name='login',
        ),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Paper(models.Model):
    title = models.CharField(max_length=150)
    comment = models.TextField(blank=True)
    #image = models.ImageField(upload_to='photos')
    paper = models.FileField(upload_to='pdfs')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app/forms.py
from django.forms import ModelForm
from .models import Paper

class PaperForm(ModelForm):
    class Meta:
        model = Paper
        fields = ['title', 'comment', 'paper', 'category']

app/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.contrib.auth.models import User
from .models import Paper, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import PaperForm
from django.contrib import messages
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    papers = Paper.objects.all().order_by('-created_at')
    return render(request, 'app/index.html', {'papers': papers})

def users_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    papers = user.paper_set.all().order_by('-created_at')
    return render(request, 'app/users_detail.html', {'user': user, 'papers':papers})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST) # Userインスタンスを作成
        if form.is_valid():
            form.save() # Userインスタンスを保存
            input_username = form.cleaned_data['username']
            input_password = form.cleaned_data['password1']
            # フォームの入力値で認証できればユーザーオブジェクト、できなければNoneを返す
            new_user = authenticate(
                username=input_username,
                password=input_password,
                )
            # 認証成功時のみ、ユーザーをログインさせる
            if new_user is not None:
            # login関数は、認証ができてなくてもログインさせることができる。(認証は上のauthenticateで実行する)
                login(request, new_user)
                return redirect('app:users_detail', pk=new_user.pk)
    else:
        form = UserCreationForm()
    return render(request, 'app/signup.html', {'form': form})

@login_required
def papers_new(request):
    if request.method == "POST":
        form = PaperForm(request.POST, request.FILES)
        if form.is_valid():
            paper = form.save(commit=False)
            paper.user = request.user
            paper.save()
            messages.success(request, "投稿が完了しました!")
        return redirect('app:users_detail', pk=request.user.pk)
    else:
        form = PaperForm()
    return render(request, 'app/papers_new.html', {'form': form})

def papers_detail(request, pk):
    paper = get_object_or_404(Paper, pk=pk)
    return render(request, 'app/papers_detail.html', {'paper': paper})

@require_POST
def papers_delete(request, pk):
    paper = get_object_or_404(Paper, pk=pk, user=request.user)
    paper.delete()
    return redirect('app:users_detail', request.user.id)

def papers_category(request, category):
# titleがURLの文字列と一致するCategoryインスタンスを取得
    category = get_object_or_404(Category, title=category)
    # 取得したCategoryに属するPaper一覧を取得
    papers = Paper.objects.filter(category=category).order_by('-created_at')
    return render(
        request, 'app/index.html', {'papers': papers, 'category': category}
    )

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>写真投稿サイト</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
    <header>
        <div class="container">
            {% for message in messages %}
                <p class="message-success">{{ message }}</p>
            {% endfor %}
            {% block content %}{% endblock %}
            <h1><a href="{% url 'app:index' %}">写真投稿サイト</a></h1>
            <div class="header-menu">
                <a href="{% url 'app:papers_new' %}">投稿</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'app:users_detail' request.user.id %}">マイページ</a>
                    <a href="{% url 'app:logout' %}">ログアウト</a>
                {% else %}
                <a href="{% url 'app:login' %}">ログイン</a>
                {% endif %}
            </div>
        </div>
    </header>
</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

{% if category %}
    <h2>カテゴリー:{{ category.title }} の検索結果</h2>
{% endif %}

{% include 'app/papers_list.html' %}
<!-- 
<div class="paper-container">
{% for paper in papers %}
    <div class="paper">
        <iframe src="{{ paper.paper.url }}" width="100%" height="300px" frameborder="0"></iframe>
        <a href="{% url 'app:papers_detail' paper.id %}">
            <iframe src="{{ paper.paper.url }}" width="100%" height="300px" frameborder="0"></iframe>
        </a>
        <div class="paper-info">
            <a href="" class="category">{{ paper.category }}</a>
            <a href="{% url 'app:users_detail' paper.user.id %}">@{{ paper.user}}</a>
        </div>
    </div>
{% endfor %}
</div> -->

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}
<form method="POST">{% csrf_token %}
    {% if form.errors %}
    <p>ユーザー名かパスワードが間違っています。</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>ユーザー名</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>

{% endblock %}

app/templates/app/papers_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div class="paper-detail">
    <img src="{{ paper.paper.url }}" class="paper-pdf">
    <div class="paper-info">
        <a href="{% url 'app:users_detail' paper.user.id %}">
            @{{ paper.user }}
        </a>
    </div>
    <h2>{{ paper.title }}</h2>
    <p>{{ paper.comment }}</p>

    <!-- 削除ボタン -->
    {% if request.user == paper.user %}
    <form method="POST" action="{% url 'app:papers_delete' paper.id %}">
        {% csrf_token %}
        <button class="btn" type="submit" onclick='return confirm("本当に削除しますか?");'>削除</button>
    </form>
    {% endif %}

</div>

{% endblock %}

app/templates/app/papers_list.html
<div class="paper-container">
{% for paper in papers %}
    <div class="paper">
        <a href="{% url 'app:papers_detail' paper.id %}">
            <iframe src="{{ paper.paper.url }}" width="100%" height="300px" frameborder="0"></iframe>
        </a>
        <div class="paper-info">

            <a href="{% url 'app:papers_category' category=paper.category %}" class="category">
                {{ paper.category }}
            </a>
            <a href="{% url 'app:users_detail' paper.user.id %}">@{{ paper.user}}</a>
        </div>
    </div>
{% endfor %}
</div>

app/templates/app/papers_new.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>
<form action="{% url 'app:papers_new' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{ form.comment }}</td>
        </tr>
        <tr>
            <th>画像</th>
            <td>{{ form.paper }}</td>
        </tr>
        <tr>
            <th>カテゴリー</th>
            <td>{{ form.category }}</td>
        </tr>
    </table>
    <button type="submit" class="btn">保存</button>
</form>

{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<h2>ユーザー登録</h2>

<form method="POST" action="{% url 'app:signup' %}">{% csrf_token %}
    <label>ユーザー名</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <input type="submit" value="登録する">
</form>

<p><a href="{% url 'app:login' %}">ログインはこちら</a></p>

{% endblock %}

app/templates/app/users_detail.html
{% extends 'app/base.html' %}

{% block content %}

<h2 class="user-name">@{{ user.username }}</h2>

{% if papers.count != 0 %}
    <p>投稿<strong>{{ papers.count }}</strong>件</p>
{% else %}
    {% if user == request.user %}
        <p>初めての投稿をしてみましょう!</p>
    {% else %}
        <p>@{{ user.username }}さんはまだ投稿していません。</p>
    {% endif %}
{% endif %}

{% include 'app/papers_list.html' %}

{% if user.is_superuser %}
<p>管理者</p>
{% else %}
<p>一般ユーザー</p>
{% endif %}

<!-- <div class="paper-container">
{% for paper in papers %}
    <div class="paper">
        <a href="{% url 'app:papers_detail' paper.id %}">
            <img src="{{ paper.image.url }}" class="paper-img">
        </a>
        <div class="paper-info">
            <a href="" class="category">{{ paper.category }}</a>
            <a href="{% url 'app:users_detail' paper.user.id %}">@{{ paper.user}}</a>
        </div>
    </div>
{% endfor %}
</div> -->

{% endblock %}